version: "3.7"
services:
  main:
    container_name: receipt_service
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - postgres_network
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    restart: unless-stopped
   
  postgres:
    container_name: receipt_postgres
    image: postgres:13
    env_file:
      - db.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
      
volumes:
  postgres:
